apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  annotations:
        cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: postgres-container
spec:
  clusterIP: None
  ports:
  - port: 5432
    name: postgresql-port
  selector:
      app: postgres-container



# apiVersion: v1
# kind: Service
# metadata:
#   name: postgres-service
# spec:
#   selector:
#     app: postgres-container
#   ports:
#       port: 5432
#       targetPort: 5432
#   type: ClusterIP
