apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres-container
    type: clusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432





