kind: Service
apiVersion: v1
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres-container
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
