apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations
spec:
  template:
    spec:
      containers:
        - name: django
          image: 1joe/stickynotes:latest
          command: ['python', 'manage.py', 'migrate']
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: PGDATA
              value: /data/pgdata
            - name: POSTGRES_HOST
              value: 127.0.0.1
      restartPolicy: Never
  backoffLimit: 5

