apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations
spec:
  template:
    spec:
      containers:
        - name: django
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: ['python', 'manage.py', 'migrate']
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres  
            - name: POSTGRES_HOST
              value: postgres
            - name: PGDATA
              value: /data/pgdata
            
      restartPolicy: Never
  backoffLimit: 2

