apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiIxam9lIiwicGFzc3dvcmQiOiJDaGVtaUA2NDY5IiwiZW1haWwiOiJhZG9kZXkxQHlhaG9vLmNvbSIsImF1dGgiOiJNV3B2WlRwRGFHVnRhVUEyTkRZNSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: "2021-02-27T15:17:35Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:.dockerconfigjson: {}
      f:type: {}
    manager: kubectl-create
    operation: Update
    time: "2021-02-27T15:17:35Z"
  name: regcred
  namespace: default
  resourceVersion: "46305"
  uid: d2adc789-5c10-4773-aef5-76156678fd70
type: kubernetes.io/dockerconfigjson

