apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2h1Yi5kb2NrZXIuY29tIjp7InVzZXJuYW1lIjoiMWpvZSIsInBhc3N3b3JkIjoiQ2hlbWlANjQ2OSIsImVtYWlsIjoiYWRvZGV5MUB5YWhvby5jb20iLCJhdXRoIjoiTVdwdlpUcERhR1Z0YVVBMk5EWTUifX19
kind: Secret
metadata:
  creationTimestamp: "2021-07-18T00:53:02Z"
  name: credentials
  namespace: default
  resourceVersion: "136448"
  selfLink: /api/v1/namespaces/default/secrets/regcred
  uid: b60be27b-a21c-406b-88d1-3ca1bc893511
type: kubernetes.io/dockerconfigjson
